repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
        exclude: src/atlantis/nodes/feature/experian.py
  - repo: https://github.com/pycqa/pydocstyle
    rev: 5.0.2 # pick a git hash / tag to point to
    hooks:
      - id: pydocstyle
